# Generated by Django 4.2.18 on 2025-12-30 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='메일링 활성화')),
                ('frequency', models.CharField(choices=[('IMMEDIATE', '즉시'), ('WEEKLY', '주간'), ('MONTHLY', '월간')], default='WEEKLY', max_length=10, verbose_name='발송 빈도')),
                ('all_categories', models.BooleanField(default=False, verbose_name='전체 카테고리 구독')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('selected_categories', models.ManyToManyField(blank=True, related_name='mailing_subscribers', to='contents.category', verbose_name='구독 카테고리')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mailing_preference', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '메일링 설정',
                'verbose_name_plural': '메일링 설정 목록',
                'db_table': 'mailing_preferences',
                'ordering': ['-created_at'],
            },
        ),
    ]
