# Generated by Django 4.2.18 on 2026-01-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_mailingpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='소셜 로그인 ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='social_provider',
            field=models.CharField(choices=[('NONE', '일반 회원가입'), ('KAKAO', '카카오'), ('GOOGLE', '구글'), ('NAVER', '네이버')], default='NONE', max_length=10, verbose_name='소셜 로그인 제공자'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('social_provider', 'NONE'), _negated=True), fields=('social_provider', 'social_id'), name='unique_social_account'),
        ),
    ]
