# Generated by Django 4.2.18 on 2026-01-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_social_id_user_social_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingpreference',
            name='kakao_notification_enabled',
            field=models.BooleanField(default=False, verbose_name='카카오톡 알림 활성화'),
        ),
        migrations.AddField(
            model_name='user',
            name='kakao_message_token',
            field=models.TextField(blank=True, null=True, verbose_name='카카오 메시지 전송용 토큰'),
        ),
    ]
