# Generated by Django 4.2.18 on 2026-02-21 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_mailingpreference_kakao_notification_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='직함/역할')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/%Y/%m/', verbose_name='사진')),
                ('bio', models.TextField(blank=True, verbose_name='소개')),
                ('order', models.IntegerField(default=0, verbose_name='정렬 순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '팀 멤버',
                'verbose_name_plural': '팀 멤버 목록',
                'db_table': 'team_members',
                'ordering': ['order', 'name'],
            },
        ),
    ]
