# Generated by Django 4.2.18 on 2025-12-28 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='카테고리명')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL Slug')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('order', models.IntegerField(default=0, verbose_name='정렬 순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='contents.category', verbose_name='상위 카테고리')),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리 목록',
                'db_table': 'categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='태그명')),
                ('slug', models.SlugField(unique=True, verbose_name='URL Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '태그',
                'verbose_name_plural': '태그 목록',
                'db_table': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL Slug')),
                ('summary', models.TextField(max_length=500, verbose_name='요약')),
                ('content_html', models.TextField(verbose_name='콘텐츠 HTML')),
                ('status', models.CharField(choices=[('DRAFT', '임시저장'), ('PUBLISHED', '공개'), ('PRIVATE', '비공개'), ('ARCHIVED', '보관')], default='DRAFT', max_length=10, verbose_name='공개 상태')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='버전')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='contents/thumbnails/%Y/%m/', verbose_name='썸네일')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('estimated_time', models.PositiveIntegerField(default=0, help_text='예상 학습 시간 (분)', verbose_name='예상 소요 시간')),
                ('difficulty', models.CharField(choices=[('BEGINNER', '초급'), ('INTERMEDIATE', '중급'), ('ADVANCED', '고급')], default='BEGINNER', max_length=20, verbose_name='난이도')),
                ('prerequisites', models.TextField(blank=True, verbose_name='선수 학습')),
                ('learning_objectives', models.TextField(blank=True, verbose_name='학습 목표')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='메타 설명')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='메타 키워드')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='최초 공개일')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contents', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contents', to='contents.category', verbose_name='카테고리')),
                ('tags', models.ManyToManyField(blank=True, related_name='contents', to='contents.tag', verbose_name='태그')),
            ],
            options={
                'verbose_name': '콘텐츠',
                'verbose_name_plural': '콘텐츠 목록',
                'db_table': 'contents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='contents.content', verbose_name='콘텐츠')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '즐겨찾기',
                'verbose_name_plural': '즐겨찾기 목록',
                'db_table': 'favorites',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'content')},
            },
        ),
        migrations.CreateModel(
            name='ContentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, verbose_name='버전')),
                ('content_html', models.TextField(verbose_name='콘텐츠 HTML')),
                ('change_log', models.TextField(verbose_name='변경 내역')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='contents.content', verbose_name='콘텐츠')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_versions', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
            ],
            options={
                'verbose_name': '콘텐츠 버전',
                'verbose_name_plural': '콘텐츠 버전 목록',
                'db_table': 'content_versions',
                'ordering': ['-created_at'],
                'unique_together': {('content', 'version')},
            },
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['status', '-created_at'], name='contents_status_7dce20_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['category', '-created_at'], name='contents_categor_c9b510_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['slug'], name='contents_slug_654087_idx'),
        ),
    ]
