# Generated by Django 4.2.18 on 2026-02-21 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contents', '0002_remove_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='assigned_writers',
            field=models.ManyToManyField(blank=True, related_name='assigned_categories', to=settings.AUTH_USER_MODEL, verbose_name='담당 작성자'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='contents.category', verbose_name='상위 카테고리'),
        ),
    ]
