# Generated by Django 4.2.18 on 2026-02-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_category_assigned_writers_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='비워두면 카테고리명에서 자동 생성됩니다.', max_length=100, unique=True, verbose_name='URL Slug'),
        ),
        migrations.AlterField(
            model_name='content',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='비워두면 제목에서 자동 생성됩니다.', max_length=200, unique=True, verbose_name='URL Slug'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='비워두면 태그명에서 자동 생성됩니다.', unique=True, verbose_name='URL Slug'),
        ),
    ]
