# Generated by Django 4.2.18 on 2026-02-22 11:19

from django.db import migrations
import django.db.models.functions.comparison


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_alter_category_slug_alter_content_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': [django.db.models.functions.comparison.Collate('name', 'C')], 'verbose_name': '태그', 'verbose_name_plural': '태그 목록'},
        ),
    ]
