# Generated by Django 4.2.18 on 2026-02-22 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_alter_tag_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='메뉴명')),
                ('url', models.CharField(blank=True, help_text='카테고리를 연결하지 않을 경우 직접 URL을 입력하세요.', max_length=500, verbose_name='커스텀 URL')),
                ('order', models.IntegerField(default=0, verbose_name='정렬 순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('open_in_new_tab', models.BooleanField(default=False, verbose_name='새 탭에서 열기')),
                ('show_subcategories', models.BooleanField(default=True, help_text='카테고리 연결 시 하위 카테고리를 드롭다운에 자동 표시합니다.', verbose_name='하위 카테고리 자동 표시')),
                ('category', models.ForeignKey(blank=True, help_text='카테고리를 연결하면 /contents?category={slug} URL이 자동 생성됩니다.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menus', to='contents.category', verbose_name='연결 카테고리')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='contents.menu', verbose_name='상위 메뉴')),
            ],
            options={
                'verbose_name': '메뉴',
                'verbose_name_plural': '메뉴 관리',
                'db_table': 'menus',
                'ordering': ['order', 'name'],
            },
        ),
    ]
