# Generated by Django 4.2.18 on 2026-02-22 12:13

from django.db import migrations, models


def migrate_menus_to_categories(apps, schema_editor):
    """Menu 모델 데이터를 Category 메뉴 필드로 이전"""
    Menu = apps.get_model('contents', 'Menu')
    Category = apps.get_model('contents', 'Category')

    # 1) 기존 루트 메뉴 중 카테고리 연결된 것 → 해당 카테고리에 show_in_menu 설정
    for menu in Menu.objects.filter(parent__isnull=True, category__isnull=False):
        cat = menu.category
        cat.show_in_menu = True
        cat.menu_order = menu.order
        if menu.name != cat.name:
            cat.menu_name = menu.name
        cat.open_in_new_tab = menu.open_in_new_tab
        cat.save()

    # 2) "디지털도서관" 메뉴 → 부모 카테고리로 전환
    #    하위 Menu 항목의 카테고리를 이 부모 아래로 이동
    for menu in Menu.objects.filter(parent__isnull=True, category__isnull=True):
        if menu.url:
            # URL 기반 메뉴 (디지털도서관, 게시판 등)
            # 하위 메뉴가 있고 카테고리 연결된 자식이 있으면 → 부모 카테고리 생성
            child_menus = Menu.objects.filter(parent=menu, category__isnull=False)
            if child_menus.exists():
                # 부모 카테고리 생성 (디지털도서관)
                parent_cat = Category.objects.create(
                    name=menu.name,
                    slug=f'menu-{menu.name}',
                    show_in_menu=True,
                    menu_order=menu.order,
                    url=menu.url,
                    open_in_new_tab=menu.open_in_new_tab,
                )
                # 자식 메뉴의 카테고리를 이 부모 아래로 이동
                for child_menu in child_menus.order_by('order'):
                    child_cat = child_menu.category
                    child_cat.parent = parent_cat
                    child_cat.save()
            else:
                # 하위 메뉴 없는 URL 메뉴 (게시판 등) → 네비게이션 전용 카테고리
                Category.objects.create(
                    name=menu.name,
                    slug=f'nav-{menu.name}',
                    show_in_menu=True,
                    menu_order=menu.order,
                    url=menu.url,
                    open_in_new_tab=menu.open_in_new_tab,
                )
        else:
            # URL 없는 드롭다운 메뉴 (소개 등) → 네비게이션 전용 부모 카테고리 + 자식들
            parent_cat = Category.objects.create(
                name=menu.name,
                slug=f'nav-{menu.name}',
                show_in_menu=True,
                menu_order=menu.order,
                url='#',
                open_in_new_tab=menu.open_in_new_tab,
            )
            for child_menu in Menu.objects.filter(parent=menu).order_by('order'):
                Category.objects.create(
                    name=child_menu.name,
                    slug=f'nav-{child_menu.name}',
                    parent=parent_cat,
                    url=child_menu.url or '',
                    order=child_menu.order,
                    open_in_new_tab=child_menu.open_in_new_tab,
                )


def reverse_migration(apps, schema_editor):
    Category = apps.get_model('contents', 'Category')
    # 네비게이션 전용 카테고리 삭제 (slug가 nav- 또는 menu-로 시작하는 것)
    Category.objects.filter(slug__startswith='nav-').delete()
    Category.objects.filter(slug__startswith='menu-').delete()
    # show_in_menu 리셋
    Category.objects.all().update(show_in_menu=False, menu_order=0, menu_name='', url='')


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0007_initial_menu_data'),
    ]

    operations = [
        # 1) Category에 메뉴 필드 추가
        migrations.AddField(
            model_name='category',
            name='menu_name',
            field=models.CharField(blank=True, help_text='비워두면 카테고리명을 메뉴명으로 사용합니다.', max_length=100, verbose_name='메뉴 표시명'),
        ),
        migrations.AddField(
            model_name='category',
            name='menu_order',
            field=models.IntegerField(default=0, help_text='메뉴에 노출 시 정렬 순서 (낮을수록 왼쪽)', verbose_name='메뉴 정렬 순서'),
        ),
        migrations.AddField(
            model_name='category',
            name='open_in_new_tab',
            field=models.BooleanField(default=False, verbose_name='새 탭에서 열기'),
        ),
        migrations.AddField(
            model_name='category',
            name='show_in_menu',
            field=models.BooleanField(default=False, help_text='체크하면 메인 화면 상단 메뉴에 표시됩니다.', verbose_name='메뉴에 노출'),
        ),
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.CharField(blank=True, help_text='설정하면 콘텐츠 카테고리가 아닌 네비게이션 전용 링크가 됩니다.', max_length=500, verbose_name='커스텀 URL'),
        ),
        # 2) Menu 데이터를 Category로 이전
        migrations.RunPython(migrate_menus_to_categories, reverse_migration),
        # 3) Menu 모델 삭제
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
