# Generated by Django 4.2.18 on 2026-02-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0008_category_menu_name_category_menu_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='summary',
            field=models.TextField(blank=True, max_length=500, verbose_name='요약'),
        ),
    ]
