# Generated by Django 4.2.18 on 2026-02-26 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0010_protect_parent_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="content",
            options={
                "ordering": ["category", "order", "-created_at"],
                "verbose_name": "콘텐츠",
                "verbose_name_plural": "콘텐츠 목록",
            },
        ),
        migrations.AddField(
            model_name="content",
            name="order",
            field=models.IntegerField(
                default=0,
                help_text="낮을수록 먼저 표시됩니다",
                verbose_name="정렬 순서",
            ),
        ),
    ]
