# Generated by Django 4.2.18 on 2026-05-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0011_add_content_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='html_source_file',
            field=models.FileField(blank=True, help_text='HTML 파일을 업로드하면 파일 내용이 콘텐츠 HTML에 자동 반영됩니다. 직접 작성하려면 비워두세요.', null=True, upload_to='contents/html/%Y/%m/', verbose_name='HTML 소스 파일'),
        ),
    ]
