# Generated by Django 4.2.18 on 2025-12-28 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='게시판명')),
                ('board_type', models.CharField(choices=[('NOTICE', '공지사항'), ('REQUEST', '콘텐츠 개발 요청'), ('QNA', '질의응답')], max_length=20, unique=True, verbose_name='게시판 타입')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '게시판',
                'verbose_name_plural': '게시판 목록',
                'db_table': 'boards',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('status', models.CharField(choices=[('PENDING', '대기'), ('IN_PROGRESS', '진행중'), ('COMPLETED', '완료'), ('REJECTED', '반려'), ('PUBLISHED', '공개')], default='PUBLISHED', max_length=20, verbose_name='상태')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='상단 고정')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='boards.board', verbose_name='게시판')),
            ],
            options={
                'verbose_name': '게시글',
                'verbose_name_plural': '게시글 목록',
                'db_table': 'posts',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='답글 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_replies', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_replies', to='boards.post', verbose_name='게시글')),
            ],
            options={
                'verbose_name': '게시글 답글',
                'verbose_name_plural': '게시글 답글 목록',
                'db_table': 'post_replies',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['board', '-created_at'], name='posts_board_i_4698f1_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', '-created_at'], name='posts_author__f2f966_idx'),
        ),
    ]
