# Generated by Django 4.2.18 on 2025-12-28 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='캠페인명')),
                ('subject', models.CharField(max_length=200, verbose_name='메일 제목')),
                ('content_html', models.TextField(verbose_name='메일 내용 (HTML)')),
                ('content_text', models.TextField(blank=True, verbose_name='메일 내용 (텍스트)')),
                ('status', models.CharField(choices=[('DRAFT', '임시저장'), ('SCHEDULED', '발송 예정'), ('SENDING', '발송 중'), ('SENT', '발송 완료'), ('FAILED', '발송 실패')], default='DRAFT', max_length=20, verbose_name='상태')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='발송 예정일')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='발송 완료일')),
                ('total_recipients', models.PositiveIntegerField(default=0, verbose_name='총 수신자 수')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='발송 성공 수')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='발송 실패 수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='email_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '이메일 캠페인',
                'verbose_name_plural': '이메일 캠페인 목록',
                'db_table': 'email_campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('is_active', models.BooleanField(default=True, verbose_name='구독 활성화')),
                ('unsubscribe_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='구독 해지 토큰')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='구독일')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='구독 해지일')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailing_subscription', to=settings.AUTH_USER_MODEL, verbose_name='연결된 사용자')),
            ],
            options={
                'verbose_name': '메일링 구독자',
                'verbose_name_plural': '메일링 구독자 목록',
                'db_table': 'mailing_list',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254, verbose_name='수신자')),
                ('status', models.CharField(choices=[('PENDING', '대기'), ('SENT', '발송 완료'), ('FAILED', '발송 실패'), ('BOUNCED', '반송됨')], default='PENDING', max_length=20, verbose_name='상태')),
                ('error_message', models.TextField(blank=True, verbose_name='오류 메시지')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='발송일')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='열람일')),
                ('clicked_at', models.DateTimeField(blank=True, null=True, verbose_name='클릭일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='mailing.emailcampaign', verbose_name='캠페인')),
            ],
            options={
                'verbose_name': '이메일 발송 로그',
                'verbose_name_plural': '이메일 발송 로그 목록',
                'db_table': 'email_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['campaign', 'status'], name='email_logs_campaig_087449_idx'), models.Index(fields=['recipient'], name='email_logs_recipie_df5c2b_idx')],
            },
        ),
    ]
